<?php

/**
 * BaseWinner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property enum $price
 * @property sfGuardUser $user
 * 
 * @method integer     getUserId()  Returns the current record's "user_id" value
 * @method enum        getPrice()   Returns the current record's "price" value
 * @method sfGuardUser getUser()    Returns the current record's "user" value
 * @method Winner      setUserId()  Sets the current record's "user_id" value
 * @method Winner      setPrice()   Sets the current record's "price" value
 * @method Winner      setUser()    Sets the current record's "user" value
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWinner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('winner');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Heladera',
              1 => 'Giftpacks',
              2 => 'Pasajes',
              3 => 'Remeras',
              4 => 'Remeras + Giftpack',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as user', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}