<?php

/**
 * BaseUserPromoCode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $promo_code_id
 * @property sfGuardUser $user
 * @property PromoCode $promoCode
 * 
 * @method integer       getUserId()        Returns the current record's "user_id" value
 * @method integer       getPromoCodeId()   Returns the current record's "promo_code_id" value
 * @method sfGuardUser   getUser()          Returns the current record's "user" value
 * @method PromoCode     getPromoCode()     Returns the current record's "promoCode" value
 * @method UserPromoCode setUserId()        Sets the current record's "user_id" value
 * @method UserPromoCode setPromoCodeId()   Sets the current record's "promo_code_id" value
 * @method UserPromoCode setUser()          Sets the current record's "user" value
 * @method UserPromoCode setPromoCode()     Sets the current record's "promoCode" value
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserPromoCode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_promo_code');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('promo_code_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('double_key_index', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'promo_code_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as user', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('PromoCode as promoCode', array(
             'local' => 'promo_code_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}