<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $facebook_uid
 * @property string $twitter_username
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $email_hash
 * @property string $profile_image
 * @property string $dni
 * @property string $phone_number
 * @property timestamp $birth_date
 * @property integer $points
 * @property sfGuardUser $user
 * 
 * @method integer            getUserId()           Returns the current record's "user_id" value
 * @method integer            getFacebookUid()      Returns the current record's "facebook_uid" value
 * @method string             getTwitterUsername()  Returns the current record's "twitter_username" value
 * @method string             getFirstName()        Returns the current record's "first_name" value
 * @method string             getLastName()         Returns the current record's "last_name" value
 * @method string             getEmailAddress()     Returns the current record's "email_address" value
 * @method string             getEmailHash()        Returns the current record's "email_hash" value
 * @method string             getProfileImage()     Returns the current record's "profile_image" value
 * @method string             getDni()              Returns the current record's "dni" value
 * @method string             getPhoneNumber()      Returns the current record's "phone_number" value
 * @method timestamp          getBirthDate()        Returns the current record's "birth_date" value
 * @method integer            getPoints()           Returns the current record's "points" value
 * @method sfGuardUser        getUser()             Returns the current record's "user" value
 * @method sfGuardUserProfile setUserId()           Sets the current record's "user_id" value
 * @method sfGuardUserProfile setFacebookUid()      Sets the current record's "facebook_uid" value
 * @method sfGuardUserProfile setTwitterUsername()  Sets the current record's "twitter_username" value
 * @method sfGuardUserProfile setFirstName()        Sets the current record's "first_name" value
 * @method sfGuardUserProfile setLastName()         Sets the current record's "last_name" value
 * @method sfGuardUserProfile setEmailAddress()     Sets the current record's "email_address" value
 * @method sfGuardUserProfile setEmailHash()        Sets the current record's "email_hash" value
 * @method sfGuardUserProfile setProfileImage()     Sets the current record's "profile_image" value
 * @method sfGuardUserProfile setDni()              Sets the current record's "dni" value
 * @method sfGuardUserProfile setPhoneNumber()      Sets the current record's "phone_number" value
 * @method sfGuardUserProfile setBirthDate()        Sets the current record's "birth_date" value
 * @method sfGuardUserProfile setPoints()           Sets the current record's "points" value
 * @method sfGuardUserProfile setUser()             Sets the current record's "user" value
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('facebook_uid', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('twitter_username', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('first_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('last_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email_address', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('email_hash', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('profile_image', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('dni', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('phone_number', 'string', 12, array(
             'type' => 'string',
             'length' => 12,
             ));
        $this->hasColumn('birth_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('points', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('twitter_username_index', array(
             'fields' => 
             array(
              0 => 'twitter_username',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as user', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $sortable0 = new Doctrine_Template_Sortable(array(
             ));
        $this->actAs($sortable0);
    }
}