<?php

/**
 * BaseTweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $twitter_guid
 * @property integer $twitter_user_id
 * @property integer $user_id
 * @property string $text
 * @property sfGuardUser $user
 * 
 * @method string      getTwitterGuid()     Returns the current record's "twitter_guid" value
 * @method integer     getTwitterUserId()   Returns the current record's "twitter_user_id" value
 * @method integer     getUserId()          Returns the current record's "user_id" value
 * @method string      getText()            Returns the current record's "text" value
 * @method sfGuardUser getUser()            Returns the current record's "user" value
 * @method Tweet       setTwitterGuid()     Sets the current record's "twitter_guid" value
 * @method Tweet       setTwitterUserId()   Sets the current record's "twitter_user_id" value
 * @method Tweet       setUserId()          Sets the current record's "user_id" value
 * @method Tweet       setText()            Sets the current record's "text" value
 * @method Tweet       setUser()            Sets the current record's "user" value
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTweet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tweet');
        $this->hasColumn('twitter_guid', 'string', 22, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 22,
             ));
        $this->hasColumn('twitter_user_id', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'string', 140, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 140,
             ));


        $this->index('twitter_guid_index', array(
             'fields' => 
             array(
              0 => 'twitter_guid',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as user', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}