<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/22 21:57:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=warsgermantour',
  'username' => 'root',
  'password' => 123456,
  'name' => 'doctrine',
)),);
