<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/19 21:21:48
sfConfig::add(array(
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'My Site',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_phirehose_class' => 'sfPhirehose',
  'app_phirehose_username' => 'songecko',
  'app_phirehose_password' => 'nevermind',
  'app_phirehose_follow' => NULL,
  'app_phirehose_track' => array (
  0 => '#quieroeldiscodelosrolling',
),
  'app_phirehose_log_purge' => 86400,
  'app_points_for_tweet' => 10,
  'app_points_for_code' => 100,
  'app_sf_guard_plugin_routes_register' => true,
  'app_twitter_api_key' => 'xC67xBHbnY6FtcS6XbQrA',
  'app_twitter_consumer_key' => 'xC67xBHbnY6FtcS6XbQrA',
  'app_twitter_consumer_secret' => 'jA8rSKEONBpLlFKGPRYx7pXU2J1px8dActWTYxTwGnU',
  'app_twitter_oauth_token' => '16963100-ETzHs0C55NjHJC9QIOEcd5C07zOZIuq54HEQuGZRi',
  'app_twitter_oauth_token_secret' => 'Qn2Zyt9bDjG6iq5r1tLAYnS3j8Nh8yQlzakLK00IDM',
));
