<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/19 21:21:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=quieroeldiscorolling',
  'username' => 'root',
  'password' => 123456,
  'name' => 'doctrine',
)),);
