<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/22 04:43:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=warsgermantour',
  'username' => 'root',
  'password' => 123456,
  'name' => 'doctrine',
)),);
