<?php
// auto-generated by sfViewConfigHandler
// date: 2013/03/20 22:23:27
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=UTF-8', false);
  $response->addMeta('title', 'German Master Tour', false, false);

  $response->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/themes/ui-darkness/jquery-ui.css', '', array ());
  $response->addStylesheet('jquery.qtip.min.css', '', array ());
  $response->addStylesheet('/js/colorbox/example5/colorbox.css', '', array ());
  $response->addStylesheet('jquery.fancybox.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js', '', array ());
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js', '', array ());
  $response->addJavascript('unitpngfix/unitpngfix.js', '', array ());
  $response->addJavascript('colorbox/colorbox/jquery.colorbox-min.js', '', array ());
  $response->addJavascript('jquery.qtip.min.js', '', array ());
  $response->addJavascript('jquery.fancybox.pack.js', '', array ());
  $response->addJavascript('sfFacebook.js', '', array ());


