<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/03/22 04:43:50
$this->security = array (
  'ajaxsignin' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
