<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/20 22:23:27
sfConfig::add(array(
  'mod_sffacebookconnectauth_enabled' => true,
  'mod_sffacebookconnectauth_view_class' => 'sfPHP',
));
