<?php

/**
 * sfGuardUserProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserProfile');
    }
    
	public function getUserRankingPosition($userId)
    {
    	Doctrine_Manager::getInstance()->getCurrentConnection()->standaloneQuery('SET @rank=0;')->execute();
    	
    	$pdo = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
    	
    	$query = "SELECT * FROM (SELECT @rank:=@rank+1 AS rank, p.`user_id` AS uid, p.`points` FROM sf_guard_user_profile AS p ORDER BY points DESC, uid ASC) AS ranking WHERE uid = :userid";
    	$stmt = $pdo->prepare($query);
    	
    	$params = array(
    		"userid"  => $userId
    	);
    	
    	$stmt->execute($params);    	
    	$results = $stmt->fetch();;
    	
    	if($results)
    	{
    		return $results['rank'];
    	}

    	return null;
    }
}