<?php

/**
 * Tweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tweet extends BaseTweet
{
	static public function hydrateFromDecodedResponse($t)
	{
		$screenName = $t->user->screen_name?$t->user->screen_name:false;
		$user = sfGuardUserTable::getInstance()->retrieveGuardUserByTwitterUsername($screenName);
		if($user)
		{
			$tweet = new Tweet();
			$tweet['twitter_guid']    = $t->id_str                   ? $t->id_str : false;
			$tweet['twitter_user_id'] = $t->user->id                 ? $t->user->id : false;
			$tweet['user_id']         = $user->getId();
			$tweet['text']            = $t->text                     ? $t->text : false;
						
			return $tweet;
		}
		
		return null;
	}
	
	public function postSave($event)
	{
		//Add points
		$user = $this->getUser();
		$user->Profile->setPoints($user->Profile->getPoints() + sfConfig::get('app_points_for_tweet'));
		$user->save();
	}
}