<?php

/**
 * Winner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Winner extends BaseWinner
{
	public function getFullname()
	{
		return $this->user->getFullname();
	}
	
	public function getClassPrice()
	{
		switch ($this->price)
		{
			case "Heladera":
				return "heladera";
				break;
			case "Giftpacks":
				return "sixpack";
				break;
			case "Pasajes":
				return "tickets";
				break;
			case "Remeras":
				return "remera";
				break;
			case "Remeras + Giftpack":
				return "remsix";
				break;
			default:
				return "";
				break;
		}
	}
}