<?php

/**
 * WinnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WinnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WinnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Winner');
    }
}