<?php

/**
 * BaseTaskLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $message
 * 
 * @method text    getMessage() Returns the current record's "message" value
 * @method TaskLog setMessage() Sets the current record's "message" value
 * 
 * @package    quieroeldiscorolling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_log');
        $this->hasColumn('message', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}