<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    warsteiner
 * @subpackage model
 * @author     Diego Damico <songecko@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function publishPost($text)
	{
		$user = sfContext::getInstance()->getUser();
		
		$access_token = $user->getAttribute('access_token');
		
		if (empty($access_token) || empty($access_token['oauth_token']) || empty($access_token['oauth_token_secret'])) 
		{
			return;
		}
		
		/* Create a TwitterOauth object with consumer/user tokens. */
		$connection = new TwitterOAuth(sfConfig::get('app_twitter_consumer_key'), sfConfig::get('app_twitter_consumer_secret'), $access_token['oauth_token'], $access_token['oauth_token_secret']);
		
		/* If method is set change API call made. Test is called by default. */
		$credentials = $connection->get('account/verify_credentials');
		
		if($credentials)
		{
			return $connection->post('statuses/update', array('status' => $text));
		}
	}
	
	/**
	 * @return String
	 */
	public function getFullname()
	{
		return $this->Profile->getFirstName().' '.$this->Profile->getLastName();
	}
	
	/**
	 * @return String
	 */
	public function getSocialName()
	{
		return ($this->Profile->getTwitterUsername())?'@'.$this->Profile->getTwitterUsername():$this->Profile->getFirstName();
	}
	
	/**
	 * @return String
	 */
	public function getSocialPicture()
	{
		if($this->Profile)
		{
			if($this->Profile->getProfileImage())
			{
				return $this->Profile->getProfileImage();
			}else
			{
				return $this->Profile->getSocialPicture();
			}
		}else
		{
			return image_path('avatar.jpg');
		}		
	}
		
	public function getRankingPosition()
	{
		return sfGuardUserProfileTable::getInstance()->getUserRankingPosition($this->getId());
	}
}